baseURL = "https://beningabaditransport.com/"
languageCode = "id-ID"
title = "Sewa Mobil Jogja Penginapan Homestay Rental Motor"
theme = "timer-hugo"
# post pagination
paginate = "15" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "SEWA MOBIL JOGJA /HOME"
url = "/"
weight = 1

[[menu.main]]
name = "Penginapan"
url = "penginapan/"
weight = 2

[[menu.main]]
name = "Sewa Motor Jogja"
url = "sewamotorjogja/"
weight = 3


[[menu.main]]
name = "Obyek Wisata Jogja/Blog"
url = "blog/"
weight = 4

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Sewa Mobil Jogja. Lepas Kunci. Sopir / Driver. Rental Motor. Penginapan. Kamar. Homestay. Murah. WA 0818 267 443"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "https://aceapugtar.cloudimg.io/gigitdemo.my.id/batik1.jpg"
heading = "SEWA MOBIL JOGJA"
description = "Rental Motor Mulai 70k/Hari | Sewa Mobil Jogja Mulai 250k/Hari | Penginapan Mulai 150k/Malam di Telpon 0274-583197 & 0274-547440. Sejak dahulu kala Bening Abadi Transport telah berkecimpung di bidang transportasi dan penginapan murah di kota pariwisata Yogyakarta dan berlokasi yang terdekat dengan UGM dan UNY Jogja serta kampus lainnya. Sewa mobil jogja, lepas kunci maupun dengan driver / sopir, sewa motor, penginapan kamar deluxe dan kamar standar serta guest house atau homestay adalah jasa utama kami dan anda bisa memesan kamar / homestay via aplikasi TRAVELOKA. Kami selalu berusaha memberikan harga yang terbaik untuk para pelanggan dan kami juga selalu senantiasa berkomitmen memberikan pelayanan yang terbaik juga kepada para pelanggan setia Bening Abadi Transport. Terima kasih banyak kepada para pelanggan yang telah menggunakan jasa kami, semoga para pelanggan kami selalu diberi sehat dan lancar serta berkah rejekinya...amien. Salam sewa mobil jogja!!"
# button
btn = false
btnText = "More"
btnURL = ""

# flip text
[[params.banner.flipText]]
title = "SEWA MOBIL YOGYAKARTA"
[[params.banner.flipText]]
title = "2023AD."
[[params.banner.flipText]]
title = "SEWA MOTOR JOGJA"
[[params.banner.flipText]]
title = "PENGINAPAN MURAH JOGJA"
[[params.banner.flipText]]
title = "ADA DI TRAVELOKA"

# Homepage About Section
[params.penginapan]
enable = false
title = "Tentang Bening Abadi Transport"
content = "<p><b>Sejak dulu kala Bening Abadi Transport telah berkecimpung di bidang transportasi dan penginapan murah di Yogyakarta dan berlokasi yang terdekat dengan UGM dan UNY Jogja dan bisa diakses melalui aplikasi TRAVELOKA. Kami selalu senantiasa berkomitmen memberikan yang terbaik kepada para pelanggan.</b></p>"
image = "https://aceapugtar.cloudimg.io/raw.githubusercontent.com/ariefbuddies/bening-out/master/uploads/m14.webp?w=400&radius=20&force_format=png&"

# Call to Action
[params.cta]
enable = true
title = "Telpon 0274-583197 & 0274-547440 Untuk informasi lebih lanjut dan booking. Syarat & Ketentuan Berlaku dibawah ini, dan nomor WA/TELPON selain di web ini adalah bukan dari pihak kami dan kami tidak bertanggungjawab selain dengan nomor telpon yg ada di web resmi kami, mohon untuk diperhatikan!"
content = "<b><ul><li>Jam Operasional 09.00 sd 22.00 WIB.</li><li>Pengantaran dan pengambilan mobil area dalam kota saja mulai jam 09.00 sd 21.00 WIB. Diluar jam diatas bisa langsung hub WA kami.</li><li><u>3 saja tanda pengenal ID</u> KTP,NPWP,SIM,PASPORT,ID KERJA,BPJS.<li><li>No HP customer yang bisa dihubungi.</li><li>Semua booking mobil lepas kunci dan motor untuk pemakaian di dalam area DIY.</li><li>Semua pemesanan tanpa DP atau uang muka adalah bersifat tidak mengikat.</li><li>Overtime 10 persen per jam dari Tarif.</li><li><u>Harga sewaktu waktu bisa berubah tanpa pemberitahuan terlebih dahulu!</u></li></ul></b>"
btnText = ""
btnURL = ""

# Portfolio Section On Homepage
[params.portfolio]
enable = false
title = "SEWA MOBIL JOGJA"
subtitle = "_______________________"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://facebook.com/beningabaditransport"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://instagram.com/beningabadi2"
