baseURL = "https://ariefbuddies.github.io/beningweb/"
languageCode = "en-us"
title = "Sewa Mobil Jogja"
theme = "timer-hugo"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Penginapan"
url = "penginapan/"
weight = 2

[[menu.main]]
name = "Sewa Mobil Jogja"
url = "/"
weight = 3

[[menu.main]]
name = "Sewa Motor Jogja"
url = "sewamotorjogja/"
weight = 4

[[menu.main]]
name = "Gallery"
url = "gallery/"
weight = 5

[[menu.main]]
name = "Obyek Wisata Jogja"
url = "blog/"
weight = 6

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 7

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Timer Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = ""
heading = "Hai, di BENING ABADI TRANSPORT kamu bisa"
description = "Rental Motor Mulai 70k/Hari | Sewa Mobil Mulai 250k/Hari | Penginapan Mulai 165k/Malam di Telpon 0274-583197 & 0274-547440"
# button
btn = false
btnText = "More"
btnURL = ""

# flip text
[[params.banner.flipText]]
title = "nyewa mobil"
[[params.banner.flipText]]
title = "minjem motor"
[[params.banner.flipText]]
title = "nginep"
[[params.banner.flipText]]
title = "tapi bayar :)"

# Homepage About Section
[params.about]
enable = true
title = "Tentang Bening Abadi"
content = "Sejak dulu kala Bening Abadi Transport telah berkecimpung di bidang transportasi dan penginapan murah di Yogyakarta dan berlolokasi yang terdekat dengan UGM dan UNY Jogja."
image = "https://aceapugtar.cloudimg.io/raw.githubusercontent.com/ariefbuddies/bening-out/master/uploads/m14.webp?w=400&radius=20&force_format=png&"

# Call to Action
[params.cta]
enable = true
title = "Telpon 0274-583197 & 0274-547440 Untuk informasi lebih lanjut dan booking"
content = ""
btnText = "Kontak kami"
btnURL = "/beningweb/contact/"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "SEWA MOBIL MURAH"
subtitle = ""

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"
