baseURL = "https://ariefbuddies.github.io/beningweb/"
languageCode = "id-ID"
title = "Sewa Mobil Jogja di Bening Abadi Transport"
theme = "timer-hugo"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Penginapan"
url = "penginapan/"
weight = 2

[[menu.main]]
name = "Sewa Mobil Jogja"
url = "/"
weight = 3

[[menu.main]]
name = "Sewa Motor Jogja"
url = "sewamotorjogja/"
weight = 4


[[menu.main]]
name = "Obyek Wisata Jogja"
url = "blog/"
weight = 5

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Sewa Mobil Jogja. Rental Motor. Penginapan. Homestay"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = ""
heading = "SEWA MOBIL JOGJA"
description = "Rental Motor Mulai 70k/Hari | Sewa Mobil Mulai 250k/Hari | Penginapan Mulai 165k/Malam di Telpon 0274-583197 & 0274-547440"
# button
btn = false
btnText = "More"
btnURL = ""

# flip text
[[params.banner.flipText]]
title = "Mo nyewa motor"
[[params.banner.flipText]]
title = "Mo nginep"
[[params.banner.flipText]]
title = "Murah"
[[params.banner.flipText]]
title = "Ga pake ribet"

# Homepage About Section
[params.penginapan]
enable = false
title = "Tentang Bening Abadi Transport"
content = "Sejak dulu kala Bening Abadi Transport telah berkecimpung di bidang transportasi dan penginapan murah di Yogyakarta dan berlokasi yang terdekat dengan UGM dan UNY Jogja."
image = "https://aceapugtar.cloudimg.io/raw.githubusercontent.com/ariefbuddies/bening-out/master/uploads/m14.webp?w=400&radius=20&force_format=png&"

# Call to Action
[params.cta]
enable = true
title = "<b>Telpon 0274-583197 & 0274-547440 Untuk informasi lebih lanjut dan booking. Syarat & Ketentuan Berlaku dibawah ini!</b>"
content = "<b><ul><li>Jam Operasional 09.00 sd 22.00 WIB.</li><li>Pengantaran dan pengambilan mobil atau motor mulai jam 09.00 sd 21.00 WIB. Diluar jam diatas bisa langsung datang ke garasi kami.</li><li><u>3 saja tanda pengenal ID</u> KTP,NPWP,SIM,PASPORT,ID KERJA,BPJS.<li><li>No HP customer yang bisa dihubungi.</li><li>Semua booking mobil lepas kunci dan motor untuk pemakaian di dalam area DIY.</li><li>Semua pemesanan tanpa DP atau uang muka adalah bersifat tidak mengikat.</li><li>Overtime 10 persen per jam dari Tarif.</li><li>Harga sewaktu waktu bisa berubah tanpa pemberitahuan!</li></ul></b>"
btnText = ""
btnURL = ""

# Portfolio Section On Homepage
[params.portfolio]
enable = false
title = "SEWA MOBIL JOGJA"
subtitle = "_______________________"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"
